apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
data:
  {{- $v := $.Files.Get "aws.yaml" | fromYaml }}
  username: {{ $v.rds.username }}
  password: {{ $v.rds.password }}
type: {{ .Values.secret.type }}